### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by Mokerstier** [SjorsWijsman/progressive-web-apps-2021#2]
https://github.com/SjorsWijsman/progressive-web-apps-2021/blob/7543ea745852c88c22e032767cbfb64ac21d5729/index.js#L18-L24

Dit is een mooi stukje voor in een aparte file bijvoorbeeld zoiets als `render.js`

**Comment by SjorsWijsman** [comment]
Deze functie bestaat door server side rendering niet meer.
