### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by Mokerstier** [SjorsWijsman/progressive-web-apps-2021#4]
https://github.com/SjorsWijsman/progressive-web-apps-2021/blob/7543ea745852c88c22e032767cbfb64ac21d5729/index.js#L5

Volgens mij kan je deze regel destructeren:
`const { getPlaylists, getPlaylist } = require('./scripts/spotifyApi');`

dan hoef je verderop in je code dit niet meer te doen:

`spotifyApi.getPlaylists((response...etc.`
maar dan kan je gewoon dit doen:
`getPlaylists((response...etc.`

**Comment by SjorsWijsman** [comment]
Destructuring toegevoegd, soms vind ik dit fijner omdat ik dan kan zien waar de functies vandaan komen, in dit geval is het prima te lezen met destructuring 👍
