### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by Mokerstier** [SjorsWijsman/progressive-web-apps-2021#5]
https://github.com/SjorsWijsman/progressive-web-apps-2021/blob/7543ea745852c88c22e032767cbfb64ac21d5729/scripts/spotifyApi.js#L1

Ik zou deze file eerder verwachten in een mapje modules of api of iets dergelijks.

In de folder scripts verwacht ik eerder scripts die je uitvoerd voor je de app deployed (buildscripts etc.)

**Comment by SjorsWijsman** [comment]
Verplaatst naar modules
